// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdqozpeuvqkyijxwssak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcW96cGV1dnFreWlqeHdzc2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTk4NzIsImV4cCI6MjA2NTc5NTg3Mn0.fAXZtMZfBesOAB2LCXybFbDULmKBSINLzgaxsgneynM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);